### ISSUE TITLE
Assignee field is shown through filters

### ISSUE THREAD

**Issue by lublasco** [planio-gmbh/redmine_issue_field_visibility#3]
Hi,

thanks for your plugin.

I'm using it to hide the "assigned to" field to certain profiles. The field is correctly hidden on the issue page, however, the user is able to view the field when using the filters. Please see attached images.
If the user selects Assgined to role or group, the assignee is shown.

![assignee_hidden](https://cloud.githubusercontent.com/assets/6445323/13565527/e32a10b6-e450-11e5-9dff-a5a3ad89bc07.jpg)
![assignee_shown](https://cloud.githubusercontent.com/assets/6445323/13565580/2e58ed00-e451-11e5-81ba-98b545c255c9.jpg)

Could you please give me some advice about it?

Many thanks in advance.

My installation:
Environment:
  Redmine version                3.2.0.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [i386-mingw32]
  Rails version                  4.2.5
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.11
  Git                            2.5.1
  Filesystem  
Redmine plugins:
  redmine_contacts               4.0.4
  redmine_contacts_helpdesk      3.0.1
  redmine_issue_field_visibility 1.0.0
  redmine_ldap_sync              2.0.8.devel
  redmine_people                 1.0.0
  redmine_tweaks                 0.5.7

**Comment by jkraemer** [comment]
The issue filter page can show issues from different projects/subprojects,  where the current user might have a different role than in the current project (also there is the global /issues page without a project context). Therefore the field is still there and can be picked as a column to be shown.

However the plugin patches Redmine in a way that for issues where the field (through the user's role in that issue's project) should be hidden, no value is shown in that column. Can you please double check if this is the case, i.e. that the current user has the Tecnico role in the project of issue 58?

There may of course be a conflict with one of your other plugins, can you point me to their sources so I can have a look?

**Comment by lublasco** [comment]
> The issue filter page can show issues from different projects/subprojects, where the current user might have a different role than in the current project (also there is the global /issues page without a project context). Therefore the field is still there and can be picked as a column to be shown.

Right.

> However the plugin patches Redmine in a way that for issues where the field (through the user's role in that issue's project) should be hidden, no value is shown in that column. Can you please double check if this is the case, i.e. that the current user has the Tecnico role in the project of issue 58?

Double checked and setup is OK.

> There may of course be a conflict with one of your other plugins, can you point me to their sources so I can have a look?

I've tested the plugin in another Redmine 3.2 installation with no other plugin. The problem remains the same: the assignee values are shown through the filters. Could it be a 3.2 incompatibility? If you don't mind I will email you the access data to this test installation so that you can check by yourself.
Many thanks in advance for your help.

**Comment by jkraemer** [comment]
Please have a look at the most recent version - I think I just fixed this.

**Comment by lublasco** [comment]
Great, now it is working perfectly! Thanks a lot for the plugin and your help!

Attached I'm sending you my two cents: the Spanish locale
[es.txt](https://github.com/planio-gmbh/redmine_issue_field_visibility/files/171598/es.txt)

**Comment by jkraemer** [comment]
thanks!
