### ISSUE TITLE
install plugin Error

### ISSUE THREAD

**Issue by kay54068** [planio-gmbh/redmine_issue_field_visibility#6]
I have a issue about this:

![image](https://cloud.githubusercontent.com/assets/3054544/23891471/7648c5d6-08d1-11e7-8d3e-1fc51f48efa5.png)

Environment:
  Redmine version                3.3.2.stable.16379
  Ruby version                   2.2.6-p396 (2016-11-15) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2

**Comment by jkraemer** [comment]
please try most recent master, I think that's been a naming conflict with another plugin that should be fixed now.
