### ISSUE TITLE
Compatibility with 3.4.2.stable

### ISSUE THREAD

**Issue by keithkuk** [planio-gmbh/redmine_issue_field_visibility#7]
Compatibility with 3.4.2.stable

Are there any plans to update the plugin to Redmine 3.4.2.stable?

Thanks a lot for your work.

**Comment by jkraemer** [comment]
We will certainly do so but there is no definite timeline yet. What problems did you encounter with 3.4.2?

**Comment by dkastl** [comment]
The plugin works for me in Redmine 3.4.2.stable

**Comment by jkraemer** [comment]
It indeed does.
