### ISSUE TITLE
Hide "priority" field

### ISSUE THREAD

**Issue by dkastl** [planio-gmbh/redmine_issue_field_visibility#9]
@jkraemer , I'm trying to figure out, how to hide the `priority` field, but it seems, that this plugin doesn't allowed it, and in a default Redmine installation I can only set the field to "read-only" but it will still be visible.

Did I miss any setting, or is there a reason, why this plugin doesn't support hiding the priority field as well?

**Comment by jkraemer** [comment]
The reason for this is that Redmine does not allow disabling of the Priority field (in the tracker config). Since the plugin hooks into this mechanism, it cannot hide this field.
